### ISSUE TITLE
additionalRequestInfo on iOS

### ISSUE THREAD

**Issue by deanle17** [sitefinitysteve/nativescript-zendesk#10]
Hello, as I would like the additional info to be appended at the end of ticket so I have created a function like this (android only):

``` js
exports.setAdditionalInfo = function (additionalInfo){
    if(typeof additionalInfo === 'string'){
      account.additionalInfo = additionalInfo;
    }
}
```

However, I have no idea how to implement it on iOS. I have tried like:

``` js
ZDKRequestCreationConfig.additionalRequestInfo= NSString.alloc().initWithString("Hola");
```

or:

``` js
ZDKRequests.configure(account,requestCreationConfig){
      requestCreationConfig.additionalRequestInfo = "This will be at the bottom of every ticket";
}
```

based on Objective-C code:

``` objective-c
[ZDKRequests configure:^(ZDKAccount *account, ZDKRequestCreationConfig *requestCreationConfig) {
    requestCreationConfig.additionalRequestInfo = @"This will be at the bottom of every ticket";
}];
```

But none of them works. Any suggestion is appreciated.

**Comment by sitefinitysteve** [comment]
Updated package on npm, allow setting of subject, tags, additional info

Keep in mind, the additionalinfo is different when sent to zendesk on android\ios (I let them know)

![image](https://cloud.githubusercontent.com/assets/1542376/14616662/5a593b46-0579-11e6-8e07-e3d27891d070.png)

Android adds the dashes, iOS just seems to append

Check the readme to see how to set the data
