### ISSUE TITLE
openHelpCenter throws an error on Android

### ISSUE THREAD

**Issue by dpdragnev** [sitefinitysteve/nativescript-zendesk#14]
Hello,

I am using NS version 3.4.3 and the latest version of nativescript-zendesk on Android version 7.0

Everything works well on iOS, but on Android I am getting an error when I execute: 

```
zd = zendeskModule.init({
        appId: appID,
        url: url,
        clientId: clientID
    });

zd.openHelpCenter();
```

The error I am getting is:

**TypeError: Cannot read property 'impl' of undefined**

The stacktrace is pointing to index.js line 158, which is this line:

```
com.zendesk.sdk.network.impl.ZendeskConfig.INSTANCE.setContactConfiguration(getConfig());
```

it seems that network resolves to 'undefined'.

Any idea how to solve this?  

Thank you

**Comment by shauntif** [comment]
Similar problem for me:
Cannot read property 'name' of undefined

After looking at the code, I added a default options with no real category and it worked.

```
this.zendesk.openHelpCenter({
                type: "none",
                id: 0,
                name: "No Category"
            });
```

**Comment by dpdragnev** [comment]
Thanks @shauntif I tried that, but still not working for me.  I am getting:

**java.lang.ClassNotFoundException: Didn't find class "retrofit2.Callback"**

What version of tns-android are you using?

**Comment by shauntif** [comment]
"nativescript-zendesk": "^0.3.4",
"nativescript": "^3.4.0-2017-12-07-10191",
    "nativescript-angular": "~4.4.1",

 "tns-ios": {
      "version": "3.3.0"
    },
    "tns-android": {
      "version": "3.4.0-2017-10-31-1"
    }

I'm stuck at this version for now.

**Comment by dpdragnev** [comment]
Hmm,  weird.  I am using the same version, but in my case I am getting the error shown in my previous post.

**Comment by shauntif** [comment]
Step through the js file of the sdk as it's running to see if anything stands out.  

Run the basics of cleaning as well:
Wipe platforms, hooks, even node_modules folder and package.lock, and re-build all etc to make sure there is no JS file bs going on.

**Comment by dpdragnev** [comment]
Thanks @shauntif 

I will have a look.  Closing this for now.
