### ISSUE TITLE
Zendesk SDK Android v1.5.1.1 / iOS v1.5.4.1

### ISSUE THREAD

**Issue by schlan** [sitefinitysteve/nativescript-zendesk#5]
Today a new version of the Zendesk Mobile SDK was released, containing bug fixes & improvements. 

Release notes:
- Android: https://developer.zendesk.com/embeddables/docs/android/release_notes#version-1.5.1.1
- iOS: https://developer.zendesk.com/embeddables/docs/ios/release_notes#version-1.5.4.1

:shipit:

**Comment by sitefinitysteve** [comment]
Thanks!
